# language: php
build:
  environment:
    php: 8.0.11
  nodes:
    tests: true
    analysis:
      dependencies:
        after:
        # The following installs the most recent XOOPS CMS version, you might want
        # to install a specific release tag or branch instead.
        - git clone --depth=1 https://github.com/XOOPS/XoopsCore25
        - git clone --depth=1 https://github.com/mambax7/tag
        - git clone --depth=1 https://github.com/mambax7/xoopspoll
        - git clone --depth=1 https://github.com/mambax7/xlanguage
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
  environment:
    php:
      version: "7.2"
filter:
  dependency_paths:
    - XoopsCore25/*
    - tag/*
    - xoopspoll
    - xlanguage
